import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,Menu,X,ArrowRight,MapPin,Mail,PlayCircle}from'lucide-react';import data from'./content/site.json';import'./styles.css';
const palette=['#d9a441','#4f8f9f','#814e36','#597d52','#7b6db4','#b86f52'];
function Header(){const[open,setOpen]=useState(false);return <><header className="top"><a className="brand" href="#top"><span className="mark">∑</span><span>Музей<br/>измерительных приборов</span></a><nav>{data.nav.map(([t,h])=><a href={h} key={t}>{t}</a>)}</nav><button className="icon" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobile">{data.nav.map(([t,h])=><a onClick={()=>setOpen(false)} href={h} key={t}>{t}</a>)}</div>}</>}
function Hero(){return <section className="hero" id="top"><div className="heroText"><p className="eyebrow">ООО «ЭРИС» · Чайковский</p><h1>Современный музей истории измерений</h1><p>Интерактивная экспозиция приборов, инженерных идей и образовательных проектов — от весов и оптики до электроизмерений и газоанализа.</p><div className="actions"><a className="btn" href="#collection">Смотреть коллекцию <ArrowRight size={18}/></a><a className="btn ghost" href="#video"><PlayCircle size={18}/> Виртуальный тур</a></div></div><div className="heroCard"><div className="orb"/><h2>1500+</h2><p>исторических приборов и уникальных предметов культурной ценности</p></div></section>}
function Stats(){return <section className="stats">{data.stats.map(s=><div><b>{s.value}</b><span>{s.label}</span></div>)}</section>}
function About(){const[more,setMore]=useState(false);return <section className="grid" id="about"><div><p className="eyebrow">История</p><h2>От сервисного предприятия КИП до открытого музея</h2>{data.history.slice(0,more?3:1).map(p=><p>{p}</p>)}<button className="link" onClick={()=>setMore(!more)}>{more?'Свернуть историю':'Развернуть историю'}</button></div><div className="panel"><h3>О музее</h3><p>{data.history[2]}</p><ul><li>экскурсии и тематические занятия;</li><li>мастер-классы для учащихся;</li><li>проектная библиотека и награды.</li></ul></div></section>}
function Featured(){return <section><p className="eyebrow">Уникальные экспонаты</p><h2>Предметы, с которых удобно начать знакомство</h2><div className="cards">{data.featured.map((f,i)=><article className="card"><div className="thumb" style={{background:`linear-gradient(135deg,${palette[i%palette.length]},#151515)`}}>{i+1}</div><h3>{f}</h3></article>)}</div></section>}
function Collection(){const[query,setQ]=useState('');const[cat,setCat]=useState('Все');const items=useMemo(()=>data.collection.filter(i=>(cat==='Все'||i.category===cat)&&i.title.toLowerCase().includes(query.toLowerCase())),[query,cat]);return <section id="collection"><div className="sectionHead"><div><p className="eyebrow">Коллекция</p><h2>Каталог экспонатов</h2></div><label className="search"><Search size={18}/><input placeholder="Поиск по каталогу" value={query} onChange={e=>setQ(e.target.value)}/></label></div><div className="chips">{data.categories.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="catalog">{items.map((i,n)=><article><span>{i.category}</span><h3>{i.title}</h3><p>Карточка готова для расширения: описание, фото, инвентарный номер, год и производитель редактируются в JSON.</p></article>)}</div></section>}
function Info(){return <section className="grid"><div className="panel" id="news"><p className="eyebrow">Новости</p>{data.news.map(n=><div className="news"><time>{n.date}</time><h3>{n.title}</h3></div>)}</div><div className="panel" id="education"><p className="eyebrow">Образование</p><h2>Экскурсии, мастер-классы и проекты</h2><p>Кураторы рассказывают о принципах измерений и работе приборов. Учащиеся демонстрируют идеи, а проекты собираются в библиотеке проектов.</p><a className="btn" href="https://disk.yandex.ru/" target="_blank">В библиотеку проектов</a></div></section>}
function Footer(){return <footer><div><b>Музей измерительных приборов</b><p><MapPin size={16}/>{data.contacts.address}</p><p><Mail size={16}/><a href={`mailto:${data.contacts.email}`}>{data.contacts.email}</a></p></div><div><a href={data.contacts.site}>Сайт ЭРИС</a><a href={data.contacts.vk}>Vk</a><span>© 2026 Все права защищены</span></div></footer>}
function App(){return <><Header/><main><Hero/><Stats/><About/><Featured/><Collection/><section className="video" id="video"><h2>Виртуальный тур</h2><p>Блок подготовлен для подключения панорам, видеоэкскурсии или iframe-тура без изменения верстки.</p></section><Info/></main><Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
